INSERT INTO produtos (nome, preco) VALUES ('Camiseta', 29.90);
INSERT INTO produtos (nome, preco) VALUES ('Calça Jeans', 89.90);
INSERT INTO produtos (nome, preco) VALUES ('Tênis', 199.90);
INSERT INTO produtos (nome, preco) VALUES ('Sapato', 199.90);
INSERT INTO produtos (nome, preco) VALUES ('Camisa', 50);
INSERT INTO produtos (nome, preco) VALUES ('Calça Capri', 89.90);
INSERT INTO produtos (nome, preco) VALUES ('Bolsa', 199.90);
INSERT INTO produtos (nome, preco) VALUES ('Blusa', 29.90);
INSERT INTO produtos (nome, preco) VALUES ('Jaqueta Jeans', 150);
INSERT INTO produtos (nome, preco) VALUES ('Mochila', 199.90);
INSERT INTO produtos (nome, preco) VALUES ('Meia', 10);
INSERT INTO produtos (nome, preco) VALUES ('Bermuda', 89.90);
INSERT INTO produtos (nome, preco) VALUES ('Terno', 199.90);
INSERT INTO produtos (nome, preco) VALUES ('Lenço', 29.90);
INSERT INTO produtos (nome, preco) VALUES ('Moletom', 89.90);
INSERT INTO produtos (nome, preco) VALUES ('Perfume', 199.90);
INSERT INTO produtos (nome, preco) VALUES ('Chinelo', 29.90);
INSERT INTO produtos (nome, preco) VALUES ('Paletó', 89.90);
INSERT INTO produtos (nome, preco) VALUES ('Relógio', 199.90);
INSERT INTO produtos (nome, preco) VALUES ('Bijuteria', 29.90);
INSERT INTO produtos (nome, preco) VALUES ('Biquini', 89.90);
INSERT INTO produtos (nome, preco) VALUES ('Mala', 199.90);